internal/pkg/mailbox/sender.go
- Send transaction
- Store message
- Encrypt message
- Encrypt location
=> Mailbox.Send Message 

.travis.yml, Makefile, cmd/mailchain/config/clients.go, cmd/mailchain/config/clients_test.go, cmd/mailchain/config/config_test.go, cmd/mailchain/config/inbox.go, cmd/mailchain/config/inbox_test.go, cmd/mailchain/config/names/clients.go, cmd/mailchain/config/pubkey_finder.go, cmd/mailchain/config/pubkey_finder_test.go, cmd/mailchain/config/receivers.go, cmd/mailchain/config/receivers_test.go, cmd/mailchain/config/senders.go, cmd/mailchain/config/senders_test.go, cmd/mailchain/config/testdata/invalid.yaml, go.mod, go.sum, internal/mailchain/commands/serve.go, internal/mailchain/commands/setup/network.go, internal/mailchain/commands/setup/pubkey_finder.go, internal/mailchain/commands/setup/receiver.go, internal/mailchain/commands/setup/sender.go
=> Remove etherscan apikey requirement

Readme.MD, internal/pkg/chains/ethereum/README.md
Create auto-generated TOC for README files
=> Add TOC to readme files

cmd/relay/commands/execute.go, cmd/relay/commands/root.go, cmd/relay/handler/handler.go, cmd/relay/handler/handler_test.go, cmd/relay/main.go, cmd/relay/relayer/relay.go, cmd/relay/relayer/relay_test.go, stores/get_test.go
=> relay command

cmd/mailchain/commands/config.go, cmd/mailchain/commands/config_ethereum.go, cmd/mailchain/commands/config_ethereum_test.go, cmd/mailchain/commands/init.go, cmd/mailchain/internal/config/defaults/default.go, cmd/mailchain/internal/config/pubkey_finder.go, cmd/mailchain/internal/config/receiver.go, cmd/mailchain/internal/config/sender.go, cmd/mailchain/internal/setup/network.go, cmd/mailchain/internal/setup/selector.go, internal/chains/ethereum/ethereum.go, sender/sender.go
=> config relay as sender by default

cmd/mailchain/internal/http/handlers/protocols.go, cmd/mailchain/internal/http/handlers/protocols_test.go, cmd/mailchain/internal/http/server.go, cmd/mailchain/internal/settings/base.go, cmd/mailchain/internal/settings/etherscan_pkf.go, cmd/mailchain/internal/settings/etherscan_receiver.go, cmd/mailchain/internal/settings/init.go, cmd/mailchain/internal/settings/network.go, cmd/mailchain/internal/settings/network_test.go, cmd/mailchain/internal/settings/protocol.go, cmd/mailchain/internal/settings/protocol_test.go
=> Add protocols end point

cmd/mailchain/internal/settings/defaults/default.go, cmd/mailchain/internal/settings/init.go, cmd/mailchain/internal/settings/init_test.go, cmd/mailchain/internal/settings/keystore.go, cmd/mailchain/internal/settings/mailbox_state.go, internal/mail/message.go
=> Put keystore and mailbox state in correct directory

internal/envelope/uint64_bytes.go, internal/envelope/uint64_bytes_test.go
=> Create Uint64 bytes type

internal/envelope/0x50.go, internal/envelope/0x50_test.go
=> Alpha envelope

.gitignore, internal/clients/etherscan/receiver.go
=> fixes messages sent to self appear twice

cmd/mailchain/internal/http/handlers/openapi.go, cmd/mailchain/internal/http/handlers/resolve_address.go, cmd/mailchain/internal/http/handlers/resolve_name.go, docs/openapi/spec.json
=> Improve resolve name api documentation

cmd/mailchain/internal/http/handlers/send_message.go, cmd/mailchain/internal/http/handlers/send_message_test.go, cmd/mailchain/internal/http/server.go, internal/envelope/data.go
=> Fix not resolving protocol in API requests

cmd/mailchain/internal/http/handlers/resolve_version.go, cmd/mailchain/internal/http/handlers/resolve_version_test.go, cmd/mailchain/internal/http/server.go
=> adds version endpoint

crypto/cipher/cipher.go, crypto/cipher/noop/decrypter.go, crypto/cipher/noop/decrypter_test.go, crypto/cipher/noop/encrypter.go, crypto/cipher/noop/encrypter_test.go
=> Create No Operation encrypter / decrypter

cmd/mailchain/internal/http/config.go, cmd/mailchain/internal/http/handlers/addresses.go, cmd/mailchain/internal/http/handlers/messages.go, cmd/mailchain/internal/http/handlers/messages_test.go, cmd/mailchain/internal/http/handlers/openapi.go, cmd/mailchain/internal/http/handlers/protocols.go, cmd/mailchain/internal/http/handlers/pubkey.go, cmd/mailchain/internal/http/handlers/pubkey_test.go, cmd/mailchain/internal/http/handlers/resolve_address.go, cmd/mailchain/internal/http/handlers/resolve_address_test.go, cmd/mailchain/internal/http/handlers/resolve_name.go, cmd/mailchain/internal/http/handlers/resolve_name_test.go, cmd/mailchain/internal/http/handlers/send_message.go, cmd/mailchain/internal/http/handlers/send_message_test.go, cmd/mailchain/internal/http/params/query.go, cmd/mailchain/internal/http/params/query_test.go, cmd/mailchain/internal/http/server.go, docs/openapi/spec.json, go.mod
=> create new config and api structure

cmd/mailchain/commands/account.go, cmd/mailchain/commands/prerun.go, cmd/mailchain/commands/root.go, cmd/mailchain/internal/prompts/func.go, cmd/relay/relayer/relay.go
=> Explicitly set `content-length` when relaying messages

cmd/mailchain/internal/http/config.go, cmd/mailchain/internal/http/handlers/messages.go, cmd/mailchain/internal/http/handlers/pubkey.go, cmd/mailchain/internal/http/handlers/pubkey_test.go, cmd/mailchain/internal/http/handlers/resolve_address.go, cmd/mailchain/internal/http/handlers/resolve_address_test.go, cmd/mailchain/internal/http/handlers/resolve_name.go, cmd/mailchain/internal/http/handlers/resolve_name_test.go, cmd/mailchain/internal/http/handlers/send_message.go, cmd/mailchain/internal/settings/etherscan_pkf.go, cmd/mailchain/internal/settings/etherscan_receiver.go, cmd/mailchain/internal/settings/nameservice_address.go, cmd/mailchain/internal/settings/nameservice_address_test.go, cmd/mailchain/internal/settings/nameservice_domain.go, cmd/mailchain/internal/settings/nameservice_domain_test.go, cmd/mailchain/internal/settings/pkf.go, cmd/mailchain/internal/settings/pkf_test.go, cmd/mailchain/internal/settings/receivers.go, cmd/mailchain/internal/settings/receivers_test.go, cmd/mailchain/internal/settings/senders.go, cmd/mailchain/internal/settings/senders_test.go, internal/address/decode.go, internal/address/decode_test.go, internal/protocols/substrate/pubkey_test.go
=> Prevent partly configure networks from erroring

internal/encoding/consts.go
=> Create encoding table

internal/keystore/nacl/store.go
=> add version to keystore

cmd/mailchain/internal/http/handlers/send_message.go
add method crypto/secp256k1.PublicKeyFromBytes()
=> #334 change secp256k1.PublicKeyFromHex to PublicKeyFromBytes

cmd/mailchain/internal/http/handlers/messages.go, cmd/mailchain/internal/http/handlers/send_message.go, internal/keystore/keystore.go, internal/keystore/keystoretest/keystore_mock.go, internal/keystore/nacl/address.go, internal/keystore/nacl/address_test.go
=> Correct method to check if keystore has address

Makefile, cmd/mailchain/internal/http/handlers/openapi.go
=> #364  Go fmt on openapi.go

internal/clients/etherscan/api.go, internal/clients/etherscan/receiver.go
=> refactor: make Decode method private

crypto/secp256k1/ecdsa_keys_test.go, crypto/secp256k1/private.go, crypto/secp256k1/public.go
=> chore: Adding missing tests or correcting existing tests

internal/clients/etherscan/pubkey-finder_test.go
test: Added tests for etherscan.getFromResultHash
fixes #408
=> test: Added tests for etherscan.getFromResultHash

cmd/mailchain/internal/http/handlers/send_message.go, cmd/mailchain/internal/http/handlers/send_message_test.go, internal/mail/headers.go, internal/mail/message.go, internal/mail/message_test.go
Adds optional content-type field on send message request.
If content-type is missing defaults to text/plain
Closes #406
=> #406 HTML Detection Fails on Send Message

cmd/indexer/internal/datastore/pq/sync.go, cmd/indexer/internal/datastore/pq/sync_test.go
=> test: SyncStore.GetBlockNumber

docker-compose.yml
=> feat: docker-compose to create postgres db

crypto/cipher/ecdh/ecdh.go, crypto/cipher/ecdh/ecdh_test.go, crypto/cipher/ecdh/errors.go, crypto/cipher/ecdh/secp256k1.go, crypto/cipher/ecdh/secp256k1_test.go, crypto/cipher/keyexchange.go, crypto/keyexchange.go, crypto/secp256k1/private.go, crypto/secp256k1/private_test.go, crypto/secp256k1/public.go, crypto/secp256k1/public_test.go
=> feat: create echd key exchange for secp256k1

crypto/cipher/ecdh/ecdh_test.go, crypto/cipher/ecdh/ed25519.go, crypto/cipher/ecdh/ed25519_test.go, crypto/ed25519/private.go, crypto/ed25519/private_test.go, go.mod, go.sum
=> feat: echd key exchange for ed25519

cmd/indexer/internal/ethereum/transaction.go
=> chore: add check to toTansaction

cmd/mailchain/internal/http/handlers/pubkey.go, cmd/mailchain/internal/http/handlers/pubkey_test.go, cmd/mailchain/internal/http/handlers/testdata/TestGetPublicKey/200-charlotte-secp256k1.json, cmd/mailchain/internal/http/handlers/testdata/TestGetPublicKey/200-sofia-secp256k1.json, cmd/mailchain/internal/http/handlers/testdata/TestGetPublicKey/406-network-not-supported.json, cmd/mailchain/internal/http/handlers/testdata/TestGetPublicKey/422-invalid-request.json, cmd/mailchain/internal/http/handlers/testdata/TestGetPublicKey/422-nil-network-finder.json, cmd/mailchain/internal/http/handlers/testdata/TestGetPublicKey/422-no-network-finder.json, cmd/mailchain/internal/http/handlers/testdata/TestGetPublicKey/500-public-key-from-address-error.json
=> feat: return public key type

crypto/multikey/kind.go, crypto/multikey/kind_test.go
=> chore: Infer key type from public key and private key

internal/protocols/ethereum/publickey.go, internal/protocols/ethereum/publickey_test.go
=> fix: GetPublicKeyFromTransaction return 64 bytes

.goreleaser.yml, cmd/indexer/Dockerfile
=> feat: cmd/indexer docker container

go.mod, go.sum
=> fix: ENS reverse lookup

cmd/mailchain/internal/http/handlers/messages_test.go, cmd/mailchain/internal/http/handlers/protocols.go, cmd/mailchain/internal/http/handlers/pubkey.go, cmd/mailchain/internal/http/handlers/resolve_address.go, cmd/mailchain/internal/http/handlers/resolve_name.go, cmd/nameservice/commands/root.go, cmd/nameservice/handler/forward.go, cmd/nameservice/handler/reverse.go, nameservice/ens/lookup.go, nameservice/errors.go, nameservice/errors_test.go, nameservice/lookup.go
=> fix: return correct code from nameservice

cmd/mailchain/internal/http/server.go
=> fix: remove need for adding passphrase twice

cmd/mailchain/internal/settings/substraterpc_test.go, go.mod, go.sum, sender/substraterpc/client.go, sender/substraterpc/client_test.go, sender/substraterpc/substraterpc_test.go
caused by centrifuge/go-substrate-rpc-client/issues/78
=> fix: fixes error call

cmd/indexer/commands/ethereum.go, cmd/indexer/commands/root.go, cmd/indexer/commands/sequenial.go, cmd/indexer/commands/substrate.go
=>  chore: Prevent to loop forever for index errors

cmd/mailchain/internal/http/handlers/messages.go
=> fix: prevent bad envelope from returning messages

.goreleaser.yml
=> fix: add 'v' prefix when creating file

encoding/base32.go, encoding/base32_test.go
=> feat: support base 32 encoding

go.sum, sender/algod/client.go, sender/algod/sender.go
=> feat: create message sender

cmd/mailchain/internal/settings/algod.go, cmd/mailchain/internal/settings/algod_test.go, cmd/mailchain/internal/settings/defaults/networks.go, cmd/mailchain/internal/settings/root_test.go, cmd/mailchain/internal/settings/senders.go, cmd/mailchain/internal/settings/testdata/TestRoot_ToYaml/comment-defaults.comment-defaults.golden.yaml, cmd/mailchain/internal/settings/testdata/TestRoot_ToYaml/include-defaults.include-defaults.golden.yaml
=> feat: add algod sender settings

stores/bdbstore/transactions.go, stores/bdbstore/transactions_test.go
fix transaction ordering so it returns latest message first
=> fix: transaction ordering

cmd/mailchain/internal/fetching/fetcher.go, cmd/mailchain/internal/fetching/fetching.go, cmd/mailchain/internal/fetching/group.go, cmd/mailchain/internal/http/handlers/fetch_messages.go, cmd/mailchain/internal/settings/algod_test.go, cmd/mailchain/internal/settings/fetcher.go, cmd/mailchain/internal/settings/root.go, cmd/mailchain/internal/settings/testdata/TestRoot_ToYaml/comment-defaults.comment-defaults.golden.yaml, cmd/mailchain/internal/settings/testdata/TestRoot_ToYaml/include-defaults.include-defaults.golden.yaml
Allow fetching to be disabled: default `false`
=> feat: fetch disabled setting

stores/bdbstore/badgerdb.go
As per the recommendation on the official badger GitHub repo on https://github.com/dgraph-io/badger/issues/246 , I have applied the fix .
=> fix: badgerdb preventing from loading on Windows

cmd/internal/http/handlers/errors.go
=> fix: api docs

internal/envelope/0x01.go, internal/envelope/0x01_test.go
- Issue: https://github.com/mailchain/mailchain/issues/428
=> fix: ISSUE#428 add check for NoOperation encrypter when creating 0x01 envelope
